CREATE TABLE dm_f101_round_f (
	from_date date NULL,
	to_date date NULL,
	chapter bpchar(1) NULL,
	ledger_account bpchar(5) NULL,
	characteristic bpchar(1) NULL,
	balance_in_rub numeric(23, 8) NULL,
	r_balance_in_rub numeric(23, 8) NULL,
	balance_in_val numeric(23, 8) NULL,
	r_balance_in_val numeric(23, 8) NULL,
	balance_in_total numeric(23, 8) NULL,
	r_balance_in_total numeric(23, 8) NULL,
	turn_deb_rub numeric(23, 8) NULL,
	r_turn_deb_rub numeric(23, 8) NULL,
	turn_deb_val numeric(23, 8) NULL,
	r_turn_deb_val numeric(23, 8) NULL,
	turn_deb_total numeric(23, 8) NULL,
	r_turn_deb_total numeric(23, 8) NULL,
	turn_cre_rub numeric(23, 8) NULL,
	r_turn_cre_rub numeric(23, 8) NULL,
	turn_cre_val numeric(23, 8) NULL,
	r_turn_cre_val numeric(23, 8) NULL,
	turn_cre_total numeric(23, 8) NULL,
	r_turn_cre_total numeric(23, 8) NULL,
	balance_out_rub numeric(23, 8) NULL,
	r_balance_out_rub numeric(23, 8) NULL,
	balance_out_val numeric(23, 8) NULL,
	r_balance_out_val numeric(23, 8) NULL,
	balance_out_total numeric(23, 8) NULL,
	r_balance_out_total numeric(23, 8) NULL
);
